import { Task, Column } from "@/types/kanban";

export const defaultCols: Column[] = [
    {
        id: "todo",
        title: "To Do",
    },
    {
        id: "in-progress",
        title: "In Progress",
    },
    {
        id: "review",
        title: "Review",
    },
    {
        id: "done",
        title: "Done",
    },
];

export const defaultTasks: Task[] = [
    {
        id: "TASK-8712",
        columnId: "todo",
        content: "Implement Authentication Flow",
        description: "## Requirements\n- Implement login using NextAuth.js\n- Support Google and GitHub providers\n- Create protected routes middleware\n\n### Acceptance Criteria\n- [ ] User can login/logout\n- [ ] Session persists on refresh",
        priority: "high",
        tags: ["Auth", "Backend"],
        assigneeIds: ["user-1"],
        subtasks: [
            { id: "st-1", content: "Setup NextAuth", completed: true },
            { id: "st-2", content: "Configure Providers", completed: false },
        ],
        comments: [
            { id: "c-1", authorId: "user-2", content: "Make sure to handle error states correctly.", createdAt: "2023-12-20T10:00:00Z" }
        ],
        createdAt: "2023-12-20T09:00:00Z",
        updatedAt: "2023-12-20T09:00:00Z",
    },
    {
        id: "TASK-8713",
        columnId: "in-progress",
        content: "Design Dashboard Layout",
        description: "Create a responsive dashboard layout using the Sidebar component.",
        priority: "medium",
        tags: ["UI", "Design"],
        assigneeIds: ["user-2"],
        subtasks: [],
        createdAt: "2023-12-21T09:00:00Z",
        updatedAt: "2023-12-21T09:00:00Z",
    },
    {
        id: "TASK-8714",
        columnId: "review",
        content: "Optimize Database Queries",
        description: "Analyze slow queries in the reporting module and add necessary indexes.",
        priority: "high",
        tags: ["Database", "Performance"],
        assigneeIds: ["user-1", "user-3"],
        subtasks: [],
        createdAt: "2023-12-22T09:00:00Z",
        updatedAt: "2023-12-22T09:00:00Z",
    },
    {
        id: "TASK-8715",
        columnId: "done",
        content: "Fix Navigation Bug",
        description: "Mobile menu was not closing on selection.",
        priority: "low",
        tags: ["Bug", "UI"],
        assigneeIds: ["user-3"],
        subtasks: [],
        createdAt: "2023-12-19T09:00:00Z",
        updatedAt: "2023-12-19T09:00:00Z",
    },
    {
        id: "TASK-8716",
        columnId: "todo",
        content: "Integrate Payment Gateway",
        description: "Setup Stripe integration for subscription payments.",
        priority: "high",
        tags: ["Payments", "Feature"],
        assigneeIds: [],
        subtasks: [],
        createdAt: "2023-12-23T09:00:00Z",
        updatedAt: "2023-12-23T09:00:00Z",
    },
    {
        id: "TASK-8717",
        columnId: "backlog",
        content: "Mobile App Offline Mode",
        description: "Implement offline support for the mobile application using SQLite.",
        priority: "medium",
        tags: ["Mobile", "Feature"],
        assigneeIds: ["user-4"],
        subtasks: [],
        createdAt: "2023-12-24T09:00:00Z",
        updatedAt: "2023-12-24T09:00:00Z",
    },
    {
        id: "TASK-8718",
        columnId: "in-progress",
        content: "Refactor API Middleware",
        description: "Clean up the API middleware chain to improve performance and logging.",
        priority: "low",
        tags: ["Backend", "Refactor"],
        assigneeIds: ["user-1"],
        subtasks: [
            { id: "st-3", content: "Audit current middleware", completed: true },
        ],
        createdAt: "2023-12-24T10:00:00Z",
        updatedAt: "2023-12-24T10:00:00Z",
    },
    {
        id: "TASK-8719",
        columnId: "review",
        content: "Update User Documentation",
        description: "Update the user guide to reflect the new dashboard features.",
        priority: "low",
        tags: ["Docs"],
        assigneeIds: ["user-2"],
        subtasks: [],
        createdAt: "2023-12-25T09:00:00Z",
        updatedAt: "2023-12-25T09:00:00Z",
    },
    {
        id: "TASK-8720",
        columnId: "backlog",
        content: "Implement Dark Mode",
        description: "Add comprehensive dark mode support across the entire application.",
        priority: "low",
        tags: ["UI", "Feature"],
        assigneeIds: [],
        subtasks: [],
        createdAt: "2023-12-26T09:00:00Z",
        updatedAt: "2023-12-26T09:00:00Z",
    }
];
